### ISSUE TITLE
classnames should be in dependencies

### ISSUE THREAD

**Issue by tirli** [synapsestudios/react-autocomplete#17]
I'm getting an error after adding this package
``` 
This module was not found:
* classnames in ./~/synapse-react-autocomplete/lib/Autocomplete.js
To install it, you can run: npm install --save classnames
```                                                                                                                                    
so classnames should be in dependencies, not in dev dependencies.

**Comment by chrisheninger** [comment]
Hi Tirli,

This project isn't being actively maintained– I would recommend this community-driven alternative– https://github.com/reactjs/react-autocomplete

Thanks for dropping an issue– I will be sure this repo gets flagged as deprecated.

**Comment by tirli** [comment]
So long, and thanks for all the fish
